### ISSUE TITLE
Error with Kubernetes secret not syncing with GCP Secret Manager secrets

### ISSUE THREAD

**Issue by anu1508k** [GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp#197]
I have installed helm csi driver with sync.secret enabled set to true. The SecretProviderClass has secretObjectName and pods have mounts .
SecretProviderClass:
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
name: xyz-job-spc
namespace: ${ENV_NAME}
spec:
provider: gcp
parameters:
ClusterRole: secretprovidersyncing-role
secrets: |

    resourceName: "projects/xyz/secrets/xyz_key_txt_${ENV_NAME}/versions/latest"
    fileName: "key.txt"
    secretObjects:
    data:
    key: xyz-key
    objectName: key.txt
    secretName: xyz-secret
    type: Opaque

Pod Spec:

 env:
   -  name: PASSWORD
       valueFrom:
         secretKeyRef:
           name: xyz-secret
           key: xyz-key
  volumeMounts:
    - name: xyz-secret
      mountPath: /etc/xyz/xyz-secret/key.txt
      readOnly: true

serviceAccountName: csi
restartPolicy: Never
volumes:
- name: xyz-secret
csi:
driver: secrets-store.csi.k8s.io
readOnly: true
volumeAttributes:
secretProviderClass: xyz-job-spc

The csi driver and provider are in kube-system namespace.

Error in the csi-driver logs: 

Last week: the "reconcile started"/"nothing to reconcile

Today: failed to mount secrets store object content" err="error connecting to provider \"gcp\": provider not found: provider \"gcp\"" pod="regional/abc-deployment-7c4c48544c-p4555"

provider logs:
created by net.(*Resolver).goLookupIPCNAMEOrder.func3
goroutine 66 [runnable]:

**Comment by anu1508k** [comment]
Error in the CSI DRIVER logs:

 the "reconcile started"/"nothing to reconcile
This error comes when csi driver and provider installed in the same namespace as the application.


Today: failed to mount secrets store object content" err="error connecting to provider "gcp": provider not found: provider "gcp"" pod="regional/abc-deployment-7c4c48544c-p4555"

This error comes when csi driver is in the kube-system namespace.

**Comment by anu1508k** [comment]
Also config connector on the cluster level is enabled. Is there a need to add the oAuth scopes for  the CSI service account  to enable APIs.

**Comment by anu1508k** [comment]
The CSI Driver logs:

pkg/mod/k8s.io/client-go@v0.24.4/tools/cache/reflector.go:167: watch of *v1.CSIDriver ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding

**Comment by anu1508k** [comment]
pkg/mod/k8s.io/client-go@v0.24.4/tools/cache/reflector.go:167: Failed to watch *v1.SecretProviderClassPodStatus: failed to list *v1.SecretProviderClassPodStatus: secretproviderclasspodstatuses.secrets-store.csi.x-k8s.io is forbidden: User "system:serviceaccount:kube-system:secrets-store-csi-driver" cannot list resource "secretproviderclasspodstatuses" in API group "secrets-store.csi.x-k8s.io" at the cluster scope


This is the error log from CSI Driver installed in Kube-system namespace.
Earlier comment has the log from the namespace where application is deployed.

**Comment by anu1508k** [comment]
Update: uninstalled CSI Driver and Provider from both the cluster. Reinstalled only on Kube-system.

Driver logs seem ok.

Provider logs: 2022-11-25 21:00:04.279 IST
{addr: :8095, caller: secrets-store-csi-driver-provider-gcp/main.go:223, msg: health server listening, ts: 1669390204279.1565, v: 0}

**Comment by anu1508k** [comment]
Update Driver logs: 

"initializing metrics backend" backend="prometheus"
2022-12-02 17:02:42.854 IST
starting manager
2022-12-02 17:02:42.957 IST
"Initializing Secrets Store CSI Driver" driver="secrets-store.csi.k8s.io" version="v1.2.4" buildTime="2022-09-07-21:10"
2022-12-02 17:02:42.957 IST
"Listening for connections" address="//csi/csi.sock"
2022-12-02 17:02:43.904 IST
Waited for 1.037287266s due to client-side throttling, not priority and fairness, request: GET:https://10.184.0.1:443/apis/billingbudgets.cnrm.cloud.google.com/v1beta1?timeout=32s
2022-12-02 17:02:44.542 IST
node: getting default node info
2022-12-02 17:02:44.579 IST
Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}

**Comment by Khooshrin** [comment]
I have replicated your error by creating a cluster, deploying the driver and the provider on it with the config connector on a cluster level enabled. The config connector enabled causes the log statements that you have mentioned in the 6th comment to be logged due to the rate limitation on the HTTP requests that is set by config connector. However, these logs are not errors, the status of the pods of deployment are indeed in the running state.You can check the same in your GCP project by going to Kubernetes Engine --> Workloads and chosing the cluster and the namespace in which the driver and provider are deployed.


Another issue that I observed is that creating a cluster with config connector enabled can lead to insufficient CPUs and hence it is possible that the driver and the provider are not deloyed on every node as stated in the DaemonSet. For this, you would have to shift from the default node pool to a custom created node pool where the number of nodes and the machine type (default set as e2-medium) may have to be modified accordingly as per the load on the cluster. For further details you can refer to: [Migrating Node Pool](https://cloud.google.com/kubernetes-engine/docs/tutorials/migrating-node-pool#step_4_migrate_the_workloads)

**Comment by amitmodak** [comment]
Thanks for reporting this issue! There does not seem to be any further action item on this issue and hence we are closing it. Please feel free to reopen this issue or file a new one if you need further assistance.
